# Generated by Django 2.2 on 2019-05-10 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('dataSet_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataSet_name', models.CharField(max_length=200, null=True)),
                ('dataSet_type', models.CharField(max_length=200, null=True)),
                ('table_name', models.CharField(max_length=200, null=True)),
                ('size', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cretetime')),
            ],
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('tree_name', models.CharField(default=0, max_length=200)),
                ('tree_type', models.CharField(max_length=200, null=True)),
                ('tree_dict', models.TextField(default=0)),
                ('detpth', models.IntegerField(default=0)),
                ('nodes_num', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cretetime')),
                ('dataSet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trees.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(max_length=200)),
                ('accuracy', models.FloatField()),
                ('ifthen', models.TextField()),
                ('content', models.TextField(null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cretetime')),
                ('dataSet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trees.DataSet')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trees.Trees')),
            ],
        ),
    ]
